image: maven:3.6.1

before_script:
  - export KekDomain=domain
  - export KekId=id
  - export KekWord=word

stages:
  - test

maven_build:
  stage: test
  script:
    - mvn verify -B
#  only:
#    - merge_requests
#    - master
#    - develop
